/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'text' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type CommentId = string;
export type ExternalBlob = Uint8Array;
export type PostId = string;
export interface PostView {
  'id' : PostId,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
  'caption' : string,
  'image' : ExternalBlob,
  'comments' : Array<Comment>,
}
export interface Profile {
  'bio' : string,
  'displayName' : string,
  'avatar' : [] | [ExternalBlob],
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'createPost' : ActorMethod<[ExternalBlob, string], PostId>,
  'createProfile' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  'deleteComment' : ActorMethod<[PostId, CommentId], undefined>,
  'follow' : ActorMethod<[Principal], undefined>,
  'getFeed' : ActorMethod<[boolean], Array<PostView>>,
  'getOwnProfile' : ActorMethod<[], [] | [Profile]>,
  'getPostsByUser' : ActorMethod<[Principal], Array<PostView>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'searchUsers' : ActorMethod<[string], Array<[Principal, Profile]>>,
  'unfollow' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];