/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Text;
export const CommentId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const PostView = IDL.Record({
  'id' : PostId,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
  'comments' : IDL.Vec(Comment),
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'createPost' : IDL.Func([ExternalBlob, IDL.Text], [PostId], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'deleteComment' : IDL.Func([PostId, CommentId], [], []),
  'follow' : IDL.Func([IDL.Principal], [], []),
  'getFeed' : IDL.Func([IDL.Bool], [IDL.Vec(PostView)], ['query']),
  'getOwnProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PostView)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
      ['query'],
    ),
  'unfollow' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Text;
  const CommentId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const PostView = IDL.Record({
    'id' : PostId,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
    'comments' : IDL.Vec(Comment),
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'createPost' : IDL.Func([ExternalBlob, IDL.Text], [PostId], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'deleteComment' : IDL.Func([PostId, CommentId], [], []),
    'follow' : IDL.Func([IDL.Principal], [], []),
    'getFeed' : IDL.Func([IDL.Bool], [IDL.Vec(PostView)], ['query']),
    'getOwnProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getPostsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Profile))],
        ['query'],
      ),
    'unfollow' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };